# Generated by Django 4.0.4 on 2022-04-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='user_id',
            new_name='user',
        ),
    ]
