# Generated by Django 4.0.4 on 2022-04-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_id_detail_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='products.product'),
        ),
    ]
