# Generated by Django 4.0.4 on 2022-04-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_detail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
